contributors = [
    { name = "xHyroM", bio = "developer - random stuff", location = "Slovakia" },
    { name = "Devanshu2310", bio = "Software developer", location = "India" },
    { name = "Mukund32", bio = "developer - software", location = "India" },
    { name = "Shivaminc", bio = "Cybersecurity", location = "India" },
    { name = "NikoDyring", bio = "Fullstack Developer", location = "Denmark" },
    { name = "Garvit-001", bio = "Software developer", location = "India" },
    { name = "xdpooja", bio = "Beginner", location = "India" },
    { name = "elmkar", bio = "Software Engineer", location = "Italy"},
    { name = "Marcelo", bio = "Developer Intern", location = "Brasil"},
    { name = "Saahil", bio = "Developer", location = "India"},
    { name = "Nitish Pal", bio = "Developer, Mathematician", location = "India" },
    { name = "YorLecaros", bio = "Backend Developer", location = "Peru" },
    { name = "Meghwant", bio = "Web Developer", location = "India" },
    { name = "Priyanshu88", bio = "Web Developer", location = "India" },
    { name = "Vmaddikera", bio = "Beginner", location = "India" },
    { name = "Kratika2314", bio= "Beginner", location = "India" },
    { name = "gobar07", bio= "Cybersecurity", location = "India" },
]
